import { runtimeTranslations } from '../../shared/runtimeText'
import { gameTranslations } from '../../shared/gameText'
import { groupTranslations, interpolate } from '../../shared/groupText'
import { useSyncExternalStore } from 'react'
import { supportedInterfaceLanguage, type InterfaceLanguage } from '../../shared/language'

export type LanguagePreference = 'system' | InterfaceLanguage
export type Preferences = { language: LanguagePreference; appearance: 'system' | 'light' | 'dark'; fontSize: number }
const key = 'douchat.general'
function systemLanguage(): InterfaceLanguage {
  const locale = typeof navigator === 'undefined'
    ? 'en'
    : navigator.languages?.[0] || navigator.language
  return supportedInterfaceLanguage(locale)
}
export function resolveInterfaceLanguage(language: LanguagePreference): InterfaceLanguage {
  return language === 'system' ? systemLanguage() : language
}
function read(): Preferences {
  try {
    const saved = JSON.parse(localStorage.getItem(key) || '{}')
    return { language: saved.language === 'zh-CN' || saved.language === 'en' ? saved.language : 'system', appearance: ['light', 'dark'].includes(saved.appearance) ? saved.appearance : 'system', fontSize: Number.isInteger(saved.fontSize) && saved.fontSize >= 0 && saved.fontSize <= 4 ? saved.fontSize : 1 }
  } catch { return { language: 'system', appearance: 'system', fontSize: 1 } }
}
let current = read()
const listeners = new Set<() => void>()
const media = matchMedia('(prefers-color-scheme: dark)')
function apply(): void {
  document.documentElement.dataset.theme = current.appearance === 'system' ? (media.matches ? 'dark' : 'light') : current.appearance
  document.documentElement.lang = resolveInterfaceLanguage(current.language)
  document.documentElement.style.setProperty('--font-scale', String([0.85, 0.92, 1, 1.1, 1.2][current.fontSize]))
}
export function setPreferences(patch: Partial<Preferences>): void {
  current = { ...current, ...patch }
  localStorage.setItem(key, JSON.stringify(current))
  apply()
  listeners.forEach((notify) => notify())
}
window.addEventListener('storage', (event) => {
  if (event.key !== key) return
  current = read(); apply(); listeners.forEach((notify) => notify())
})
media.addEventListener('change', apply)
window.addEventListener('languagechange', () => {
  apply()
  if (current.language === 'system') listeners.forEach((notify) => notify())
})
apply()
export function usePreferences(): Preferences {
  return useSyncExternalStore((notify) => { listeners.add(notify); return () => { listeners.delete(notify) } }, () => current, () => current)
}
export function t(text: string): string {
  if (resolveInterfaceLanguage(current.language) !== 'zh-CN') return text
  const exact = translations[text]
  if (exact) return exact

  const patterns: Array<[RegExp, (...matches: string[]) => string]> = [
    [/^The owner of "(.+)" has disabled requests from group members\.$/, (_all, name) => `「${name}」的主人未开放群成员调用，请联系主人调整 Agent 权限。`],
    [/^Permissions for "(.+)" have not synchronized\. Ask the owner to reconnect\.$/, (_all, name) => `「${name}」的调用权限尚未同步，请主人重新连接后再试。`],
    [/^Runtime download failed \((\d+)\)\. Check your connection and try again\.$/, (_all, status) => `运行环境下载失败（${status}），请检查网络后重试。`],
    [/^(.+) could not deliver a message to another bot\.?$/, (_all, name) => `${name} 无法向其他智能体传递消息。`],
    [/^(.+) has no model to answer with\.?(?: (.*))?$/, (_all, name, detail) => `${name} 没有可用于回复的模型。${detail ?? ''}`],
    [/^(.+) finished without a text response\.?$/, (_all, name) => `${name} 未返回文字内容。`],
    [/^(?:429:\s*)?.*Douchat credit balance is insufficient.*$/i, () => 'Douchat 点数不足，暂时无法完成此请求。'],
    [/^Model (.+) is not available$/, (_all, model) => `模型 ${model} 当前不可用`],
    [/^Login service returned (\d+)\. Try again\.$/, (_all, status) => `登录服务返回 ${status}，请重试。`],
    [/^The gateway rejected the model list \((\d+)\)$/, (_all, status) => `模型服务拒绝了模型列表请求（${status}）`]
  ]
  for (const [pattern, replace] of patterns) {
    const match = pattern.exec(text)
    if (match) return replace(...match)
  }

  const prefixes: Array<[string, string]> = [
    ['Unexpected test response:', '测试返回了非预期内容，请检查启动参数：'],
    ['The model endpoint rejected the request', '模型服务拒绝了请求'],
    ['The model endpoint was not found', '未找到模型服务'],
    ['The model endpoint timed out', '模型服务请求超时'],
    ['The provider is rate limiting this key', '模型服务对当前密钥进行了限流'],
    ['The provider returned a server error', '模型服务返回服务器错误'],
    ['Could not reach the model endpoint', '无法连接模型服务'],
    ['Lost the connection to the model endpoint', '与模型服务的连接已中断'],
    ['The conversation could not finish', '对话未能完成']
  ]
  const prefix = prefixes.find(([source]) => text.startsWith(source))
  return prefix ? `${prefix[1]}${text.slice(prefix[0].length)}` : text
}
export function tr(text: string, values: Record<string, string | number>): string {
  return interpolate(t(text), values)
}
const translations: Record<string, string> = {
  "Activity": "活动",
  "Add project": "添加项目",
  "Agent wants to:": "智能体想要：",
  "Already modified": "已有修改",
  "Approval needed": "需要批准",
  "Cancel session": "取消会话",
  "Changed during this session": "本次会话期间的更改",
  "Changed files": "已更改的文件",
  "Checks": "检查",
  "Choose a project, or add a local repository.": "请选择项目，或添加本地代码仓库。",
  "Continue": "继续",
  "Continue the conversation": "继续对话",
  "Finished": "已结束",
  "Full task": "完整任务",
  "Git shows that these changed while the session ran, not who changed them.": "Git 只能显示这些文件在会话期间发生了变化，无法说明是谁改的。",
  "HEAD moved:": "HEAD 已移动：",
  "Modified before the session, clean now:": "会话开始前已修改、现已还原：",
  "No check command is set for this project.": "此项目尚未设置检查命令。",
  "No differences from the last commit.": "与最近一次提交没有差异。",
  "No files changed during this session.": "本次会话期间没有文件发生更改。",
  "No projects yet. Add a local repository to let an agent work in it.": "还没有项目。添加本地代码仓库，让智能体在其中工作。",
  "No sessions yet.": "还没有会话。",
  "Output": "输出",
  "Projects": "项目",
  "Result": "结果",
  "Run checks": "运行检查",
  "Running…": "运行中…",
  "Sessions": "会话",
  "Set…": "设置…",
  "Start a coding session": "开始编码会话",
  "Start session": "开始会话",
  "Started": "开始于",
  "Task": "任务",
  "Tell the agent what to do next…": "告诉智能体接下来做什么…",
  "The diff was cut short.": "差异内容已被截断。",
  "These were modified before the session started and are unchanged since.": "这些文件在会话开始前就已被修改，此后没有变化。",
  "This agent has not reported step-by-step activity. Douchat shows approvals, checks and repository changes.": "此智能体不会逐步汇报进度。Douchat 只显示批准请求、检查结果和仓库中的更改。",
  "This session was interrupted when Douchat closed.": "Douchat 关闭时，此会话被中断。",
  "Untracked — not included in git diff": "未跟踪文件——不包含在 git diff 中",
  "What should the agent do in this project?": "希望智能体在此项目中做什么？",
  "cancelled": "已取消",
  "timed out": "已超时",
  "Waiting for approval": "等待批准",
  "Succeeded": "成功",
  "Cancelled": "已取消",
  "Interrupted": "已中断",
  "Untracked": "未跟踪",
  "Modified": "已修改",
  "Deleted": "已删除",
  "Renamed": "已重命名",
  "Conflict": "冲突",
  "A new agent process will be started in this project. The previous process will not be resumed.": "将在此项目中启动新的智能体进程，之前的进程不会被恢复。",
  "The agent’s own conversation is picked up again where its CLI supports it; the project and session context are provided too.": "若其命令行工具支持，将接续智能体自己的对话；同时也会提供项目和会话上下文。",
  "Continue will start a new conversation with the existing project/session context.": "“继续”将带着现有的项目和会话上下文开始一段新对话。",
  "Reading skill file {name}": "正在读取技能文件 {name}",
  "Read skill file {name}": "已读取技能文件 {name}",
  "Could not read skill file {name}": "未能读取技能文件 {name}",
  "Listing skill files": "正在查看技能文件列表",
  "Listed skill files": "已查看技能文件列表",
  "Could not list skill files": "未能查看技能文件列表",
  'Thinking level': '思考等级',
  'Off': '关闭', 'Minimal': '极低', 'Low': '低', 'Medium': '中', 'High': '高', 'Extra high': '超高', 'Max': '最高',
  'Default ({level})': '默认（{level}）',
  'Use agent’s thinking setting': '跟随智能体自身配置',
  'Thinking': '思考',
  'The model accepts a thinking level': '该模型支持设置思考等级',
  'This model is not marked as supporting thinking. Enable it in Settings → Models.': '该模型未标记为支持思考，可在 设置 → 模型 中勾选“思考”。',
  'This local agent does not support a thinking level.': '该本地智能体暂不支持设置思考等级。',
  'Higher levels answer more carefully but slower and cost more.': '等级越高回答越审慎，但更慢、消耗更多。',
  'Workspace': '工作区',
  'Default': '默认',
  'Open folder': '打开文件夹',
  'Default (managed by Douchat)': '默认（由 Douchat 管理）',
  'Choose folder': '选择文件夹',
  'Change folder': '更换文件夹',
  'Use default': '恢复默认',
  'Not in effect: this chat now includes members other than your own agents.': '当前未生效：这个聊天里有除你自己的智能体以外的成员，将使用默认工作区。',
  'Agents in this group share this folder.': '群里的智能体共用这个文件夹。',
  'Waiting for another agent to finish in this workspace': '等待其他智能体在该工作区完成当前任务',
  'Only chats whose members are all your own agents can use a custom workspace.': '只有成员全部是你自己的智能体的聊天才能指定工作区。',
  'Chat members changed. Try again.': '聊天成员已变化，请重试。',
  'The disk root cannot be used as a workspace.': '不能把磁盘根目录设为工作区。',
  'Your home folder cannot be used directly. Choose a project folder inside it.': '不能直接使用用户主目录，请选择其中的某个项目文件夹。',
  'System folders cannot be used as a workspace.': '不能把系统文件夹设为工作区。',
  "Douchat's data folder cannot be used as a workspace.": '不能把 Douchat 的数据目录设为工作区。',
  "Group memory": "群记忆",
  "About me": "关于我",
  "Updating user memory": "正在更新用户记忆",
  "Updated user memory": "已更新用户记忆",
  "Could not update user memory": "未能更新用户记忆",
  'Remove picture': '移除头像',
  "Edit local agent": "编辑本地智能体",
  "Add local agent": "添加本地智能体",
  "Executable path": "可执行文件路径",
  "Startup arguments": "启动参数",
  "One argument per line. Added to the built-in launch arguments.": "每行一个参数，将附加到内置启动参数中。",
  "One argument per line. Use {prompt} for the message; otherwise it is appended as the last argument.": "每行一个参数。用 {prompt} 表示消息内容；未填写时，消息会作为最后一个参数传入。",
  "Testing sends a short request using this CLI’s account and may use its quota.": "测试将使用此工具的账号发送一条简短请求，可能消耗其额度。",
  "Enter valid startup arguments.": "请填写有效的启动参数。",
  "Choose a PNG, JPEG or WebP avatar.": "请选择 PNG、JPEG 或 WebP 格式的头像。",
  "Executable not found. Check the path and executable permissions.": "未找到可执行文件，请检查路径和执行权限。",
  "Connection test timed out after 30 seconds.": "连接测试超过 30 秒，请检查本地工具的登录状态及网络。",
  "Connection test cancelled.": "已取消连接测试。",
  "A connection test is already running.": "连接测试正在进行中。",

  'Model source': '模型来源',
  'Custom Model': '自定义模型',
  'Follow default model': '跟随默认模型',
  'Default model': '默认模型',
  'Set a default model in Settings first.': '请先在模型设置中配置默认模型。',
  'Agents following the default will use this model for their next reply. Individually selected models stay unchanged.': '选择跟随默认模型的智能体将在下次回复时使用此模型，单独指定模型的智能体不受影响。',
  'Reset context': '重置上下文',
  'Context reset': '上下文已重置',
  'Reset context? The current reply will stop and future replies will start fresh. Chat history will be kept.': '确认重置上下文？正在进行的回复会停止，后续对话将重新开始，聊天记录会保留。',
  'Reset context for your future requests? Chat history will be kept. Other members will not be affected.': '确认重置上下文？你之后发起的请求将不再携带此前的聊天内容，聊天记录会保留，不影响其他成员。',
  'Only the group owner can mention everyone.': '只有群主可以 @ 全体成员。',
  'The owner declined this request': '主人拒绝了这次请求。',
  'Permission request expired': '等待主人确认超时，这次请求未执行。',
  'Permission request cancelled': '这次请求已取消。',
  'The owner declined the operation, or permission expired': '这次请求未获授权（被拒绝或已超时）。',
  'The owner has disabled this permission': '主人未开放这项权限。',
  'Agent account changed': 'Agent 所属账号已切换，这次请求已取消。',
  '{first}, {second} and others ({count} members)': '{first}、{second}等 {count} 人',
  ...runtimeTranslations,
  ...groupTranslations,
  ...gameTranslations,
  'Local agent detection timed out. Check your shell startup configuration and try again.': '本地智能体检测超时，请检查终端启动配置后重试。',
  'Could not confirm the latest version. Detect again later.': '无法确认最新版本，请稍后重新检测',
  'Version unconfirmed': '版本未确认',
  'Install': '安装',
  'Update': '更新',
  'Latest version: {version}': '最新版本：{version}',
  'Preparing…': '正在准备…',
  'Installation instructions': '安装说明',
  'Preparing to install or update. Downloading the runtime for the first time may take a few minutes.': '正在准备安装或更新，首次下载运行环境可能需要几分钟，请稍候。',
  'Edit {name}': '编辑 {name}',
  'Delete {name}': '删除 {name}',
  '{name} (unavailable)': '{name}（不可用）',
  'Remove {name}? Agents using these models will be unable to chat until reconfigured. Chat history will be kept.': '删除 {name}？使用这些模型的智能体将暂时无法对话，聊天记录会保留。',
  "Actions": "操作",
  "API URL": "API 地址",
  "API type": "API 类型",
  "Identifier": "标识名",
  "Custom model provider": "自定义模型服务商",
  "Use your configured model service": "使用你配置的模型服务",
  "Local AI tools on your computer": "电脑上的本地 AI 工具",
  "Could not load custom models. Try again in Settings.": "无法加载自定义模型，请到设置中重试。",
  "Use Douchat cloud models with pay-as-you-go credits.": "按需充值，使用 Douchat 云端模型。",
  "Use your own API key. Your model provider handles billing.": "使用你自己的 API 密钥，费用由模型服务商收取。",
  "View credits": "查看额度",
  "Loading model settings…": "正在加载模型配置…",
  "Enter a model ID manually": "手动输入模型 ID",
  "Use the local agent’s model configuration.": "使用本地智能体的模型配置。",
  "Choose a model": "请选择模型",
  "Connect your model services to use when creating agents. Each provider handles billing.": "接入自己的模型服务，创建智能体时即可选择。费用由对应服务商收取。",
  "Add provider": "添加服务商",
  "Edit provider": "编辑服务商",
  "No providers yet": "尚未添加服务商",
  "Add a provider to create agents with your own models.": "添加服务商后，即可使用自己的模型创建智能体。",
  "Supports OpenAI Chat Completions and Anthropic Messages": "支持 OpenAI Chat Completions 和 Anthropic Messages",
  "Supports Ollama, OpenAI Chat Completions and Anthropic Messages": "支持 Ollama、OpenAI Chat Completions 和 Anthropic Messages",
  "Use detected Ollama": "使用检测到的 Ollama",
  "Save this provider to keep the new credential on this device.": "保存服务商后，新凭证会加密保存在本机。",
  "Your saved credential is ready to use. Authorize again only to replace it.": "可直接使用已保存的凭证；如需更换，可重新授权。",
  "Continue in your browser. No API key to copy.": "在浏览器中完成授权，无需复制 API Key。",
  "Create an API key on the provider website, then paste it above.": "前往服务商网站创建 API Key，然后粘贴到上方输入框。",
  "Credential saved": "凭证已保存",
  "Authentication method": "授权方式",
  "OAuth (recommended)": "OAuth（推荐）",
  "Enter API key manually": "手动填写 API Key",
  "Authorize in your browser to connect TokenDance without copying an API key. Save the provider after authorization.": "在浏览器中授权即可连接 TokenDance，无需复制 API Key。授权完成后请保存服务商。",
  "Waiting for browser authorization…": "等待浏览器授权…",
  "Authorize again": "重新授权",
  "Authorize TokenDance": "授权连接 TokenDance",
  "Cancel authorization": "取消授权",
  "Authorization successful. Save to finish.": "授权成功，请保存服务商。",
  "A saved API key is available.": "已保存 API Key，可直接使用或重新授权。",
  "Create an API key": "前往创建 API Key",
  "TokenDance authorization cancelled.": "TokenDance 授权已取消。",
  "TokenDance authorization declined.": "TokenDance 授权被拒绝。",
  "TokenDance authorization failed. Please try again.": "TokenDance 授权失败，请重试。",
  "TokenDance authorization timed out. Please try again.": "TokenDance 授权超时，请重试。",
  "Could not start TokenDance authorization.": "无法启动 TokenDance 授权。",
  "Could not open the authorization page.": "无法打开授权页面。",
  "Provider preset": "服务商预设",
  "Other / Custom": "其他 / 自定义",
  "e.g. openrouter": "例如 openrouter",
  "e.g. OpenRouter": "例如 OpenRouter",
  "Leave empty to keep the saved key": "留空保留已保存的密钥",
  "Enter API key": "输入 API Key",
  "Models (ID / display name)": "模型（标识名 / 显示名）",
  "Model ID ": "模型标识名 ",
  "Model display name ": "模型显示名 ",
  "Remove model ": "删除模型 ",
  "Model ID, e.g. org/model": "模型标识名，例如 org/model",
  "Display name (optional)": "显示名（可选）",
  "Add model": "添加模型",
  "The connection test sends a short message to the first model and may incur a small charge.": "连接测试会向第一个模型发送一条简短消息，可能产生少量费用。",
  "Test endpoint: ": "测试地址：",
  "Connection successful": "连接成功",
  'Dr. Dou': '豆博士', 'Douchat assistant': 'Douchat 云端助手', 'System administrator': '系统管理员', 'Built-in': '内置',
  'Could not reach the login service. Check your connection and try again.': '无法连接登录服务，请检查网络后重试。', 'This login request has expired. Start again.': '本次登录请求已过期，请重新开始。', 'The login request expired or was already used. Start again.': '本次登录请求已过期或已经使用，请重新开始。', 'Authorization code is invalid, expired, or already used': '授权码无效、已过期或已经使用，请重新开始。', 'Login callback could not be verified': '无法验证登录回调，请重新开始。', 'Login callback did not include a valid authorization code': '登录回调中没有有效的授权码。', 'Login service returned an invalid session.': '登录服务返回了无效会话。', 'Login service returned an invalid user.': '登录服务返回了无效用户信息。', 'Secure credential storage is unavailable on this computer.': '此电脑无法使用安全凭证存储。', 'Douchat Cloud Chat is not enabled or its upstream model is not configured.': 'Douchat Cloud Chat 尚未启用，或上游模型尚未配置。', 'Finish signing in in your browser. Douchat will return automatically.': '请在浏览器中完成登录，成功后将自动返回 Douchat。', 'Login could not be completed': '登录未完成', 'Checking your login…': '正在检查登录状态…',
  'Search group members': '搜索群成员', 'Remove group members': '移出群成员', 'Select members to remove': '从左侧选择要移出的群成员', 'Keep at least one member': '群聊至少保留一位成员',
  'Group members': '群聊成员', 'Create group': '创建群聊', 'Add group members': '添加群成员', 'Already added': '已加入', 'Selected agents': '已选智能体', 'Selected': '已选择', 'Select contacts to add': '从左侧选择要添加的联系人', 'Select agents to add': '从左侧选择要添加的智能体', 'No matching agents': '没有匹配的智能体',
  'Existing groups': '已有群聊', 'Open group': '进入群聊', 'Open chat': '进入聊天', 'No matching groups': '没有匹配的群聊', 'Select one agent to chat, several to create a group, or open an existing group.': '选择一个智能体开始聊天，选择多个智能体创建群聊，或直接进入已有群聊。',
  "Configure model": "配置模型",
  "WeChat": "微信",
  "Feishu": "飞书",
  "Sent via {channel}": "来自{channel}",
  "Configure message channels": "配置消息渠道",
  "Only local agents support model configuration": "只有本地 agent 支持配置模型",
  "Local only": "仅本地",
  "Cloud default": "云端默认模型",
  "Search models": "搜索模型",
  "Use agent default": "跟随智能体默认模型",
  "Loading models…": "正在加载模型…",
  "Model ID": "模型 ID",
  "Leave empty to use agent default": "留空则跟随智能体默认模型",
  "Enter the model ID configured in your local agent.": "请输入本地智能体中配置的模型 ID。",
  "No matching models": "没有匹配的模型",
  "Could not load models. Retry or enter a model ID.": "模型加载失败，请重试或手动输入模型 ID。",
  "Applies to this agent’s next conversation turn. Model access depends on your provider and account.": "下次对话生效。模型是否可用取决于服务商和账号权限。",
  "This tool does not support a per-conversation model override.": "此工具暂不支持为单个对话指定模型。",
  'Model': '模型',
  'Custom model': '自定义模型',
  'Run mode': '运行方式',
  'Agent': '智能体', 'Edit agent': '编辑智能体', 'Agent menu': '智能体菜单', 'Delete agent': '删除智能体', 'Avatar': '头像', 'Choose emoji': '选择表情', 'Use default avatar': '使用默认头像', 'Nickname': '昵称', 'Description': '描述', 'Add a description': '添加更多描述信息', 'Search or create labels': '搜索或创建标签…', 'Done': '完成', 'This picture could not be used.': '无法使用这张图片。', 'Role': '角色',
  'Share local logs to help troubleshoot display errors.': '分享本地日志，帮助排查显示异常。',
  'Open log folder': '打开日志目录',
  'Sign in to Douchat': '登录 Douchat',
  'Continue in your browser to securely sign in and get started.': '在浏览器中安全登录，即可开始使用。',
  'Get started': '开始使用',
  'Reopen browser': '重新打开浏览器',
  'Continue in your browser': '在浏览器中继续',
  'A desktop workspace where AI agents work and talk together.': '让 AI 智能体一起工作、对话的桌面工作台。',
  'Development': '开发版',
  'Desktop': '桌面版',
  'Software update': '软件更新',
  'Links': '链接',
  'Official website': '官网',
  'Report an issue': '反馈问题',
  'AGPL-3.0-only license': 'AGPL-3.0-only 许可证',
  'Could not open dialog': '弹框打开失败', 'Myself': '自己', 'Friend': '朋友', 'Edit profile': '编辑资料', 'Cursor needs workspace trust': 'Cursor 需要确认工作目录信任', 'Cursor could not start in the temporary chat workspace. Update Douchat and try again.': 'Cursor 未能在临时聊天目录中启动，请更新 Douchat 后重试。', 'Owned by': '所属成员', 'This agent belongs to another member. Direct messaging is not available.': '这是其他成员的智能体，暂不支持直接私聊。', 'Agent details': '智能体资料', 'Instructions': '行为指令', 'Labels': '标签', 'More information': '更多信息', 'Shared groups': '共同群聊', 'Source': '来源', 'Cloud': '云端', 'Local': '本地', 'Cloud model': '云端模型', 'Local model': '本地模型', 'Local agent': '本地智能体', 'Model endpoint': '模型服务', 'Added on': '添加时间',
  "Results may be visible to everyone in this group.": "执行结果可能对全体群成员可见。",
  "Human member": "真人成员",
  "Agent permissions": "智能体权限",
  "No confirmation": "不用确认",
  "Do not run": "禁止运行",
  "Requests from other people": "群友可以向它提问或派任务",
  "Requests from other agents": "其他智能体可以向它派任务",
  "Run on my computer": "替别人做事前，是否需要我确认",
  "Let other people in the group ask this agent questions or give it tasks.": "控制其他真人能否在群里 @ 它、让它回答或做事。",
  "Let other agents in the group send tasks to this agent.": "控制群里其他智能体能否请求它帮忙。",
  "After accepting someone else’s request, ask me before starting the local agent — even just to chat.": "收到他人请求后，启动本地智能体前再检查这一项，普通聊天也一样。",
  "Ask me each time": "每次问我",
  "Who can send it requests?": "谁可以找它帮忙",
  "When should it ask me?": "执行前要不要问我",
  "What can it do for others?": "帮别人做事时，可以做什么",
  "These settings only apply when someone else asks your agent to do something. Your own requests are unchanged.": "只限制别人发起的请求。你自己让它做事，不受这里的设置影响。",
  "Allowing a run may let the agent read files, execute commands and access the internet on your computer. Codex Computer Use requests separate approval; other internal actions are controlled by the local agent.": "注意：允许后，它可能读取你电脑上的文件、执行命令或联网。Codex 的桌面控制会单独请求确认，其他内部操作由本地智能体控制。",
  "Who can interact in groups": "群聊互动权限",
  "Other members’ agents": "其他成员的智能体",
  "Sensitive operations from external requests": "外部请求的敏感操作权限",
  "Read local files": "读取本地文件",
  "Modify local files": "修改本地文件",
  "Access the web": "访问网络",
  "Operate the browser": "操作浏览器",
  "Read connected accounts": "读取已连接的账号",
  "Send or modify account data": "发送或修改账号数据",
  "Create scheduled tasks": "创建定时任务",
  "Run the local agent program": "运行本地智能体程序",
  "Other tools": "其他工具",
  "Run a terminal command": "执行终端命令",
  "Run requested operation": "执行所请求的操作",
  "Read a file": "读取文件",
  "Write a file": "写入文件",
  "Edit a file": "修改文件",
  "Find files": "查找文件",
  "Search file contents": "搜索文件内容",
  "Read a web page": "读取网页",
  "Search the web": "搜索网页",
  "This runs the command below on your computer.": "将要在你的电脑上执行以下命令。",
  "Full request details": "完整请求详情",
  "Allow": "允许",
  "Ask every time": "每次询问",
  "Deny": "禁止",
  "Permission required": "需要你的授权",
  "Requested by": "请求来自",
  "Allow for this task": "本次任务内允许",
  "Access a desktop app": "访问桌面应用",
  "Application": "应用",
  "Allow this agent to view and interact with this app through Computer Use.": "允许此联系人通过 Computer Use 查看和操作这个应用。",
  "Allow this app for this session": "本次会话允许此应用",
  "Session approval applies only to this app. Other apps and separate sensitive-action confirmations still require approval.": "仅对当前应用生效，换应用或遇到单独的敏感操作确认时仍会询问。",
  "Expires when the native session closes, including idle cleanup, stop, reset or app restart.": "原生会话关闭后失效，包括闲置释放、停止任务、重置会话或重启应用。",
  "Choose once or allow this app for this session. No response within 10 minutes means deny.": "可仅允许本次，或在本次会话内允许此应用。10 分钟内未处理将自动拒绝。",
  "Allow this operation once, or reuse approval within the scope above for this task. No response within 10 minutes means deny.": "可以仅允许这次，或在本次任务的上述范围内复用授权。10 分钟内未确认则拒绝。",
  "Task approval scope": "本次授权范围",
  "Expires when this task ends. Other resources still require approval.": "任务结束后失效，访问其他资源仍需确认。",
  "Allow once": "仅允许本次",
  "This approval is for this operation only. No response within 10 minutes means deny.": "仅授权本次操作，10 分钟内未处理将自动拒绝。",
  "These permissions apply to requests from group members and agents. Your own direct instructions are unchanged.": "以下权限适用于群成员和智能体发起的请求，不影响你自己的直接指令。",
  "Local programs use their own tools and permissions. Approval can grant access to files, commands and the network. Douchat cannot enforce each tool permission inside them.": "本地程序使用自身的工具和权限。授权后可能读取文件、运行命令和访问网络，Douchat 无法逐项拦截其内部工具。",
  'Running a command': '正在执行命令',
  'Updating files': '正在更新文件',
  'Searching the web': '正在搜索网页',
  'Generating an image': '正在生成图片',
  'Generating an image; waiting for the tool result': '正在请求生成图片，等待画图工具返回',
  'Image generated; preparing the result': '图片已生成，正在整理结果',
  'Attaching generated images': '正在回传生成的图片',
  'Image generation failed': '图片生成失败',
  'Running a tool': '正在执行工具',
  'Grok did not generate an image': 'Grok 未能生成图片',
  'Gemini did not generate an image': 'Gemini 未能生成图片',
  'Gemini stopped before completing the task': 'Gemini 在任务完成前停止了',
  'Gemini image generation needs an API key': 'Gemini 画图需要配置 API 密钥',
  'Configure a Google AI Studio key locally with gemini extensions config nanobanana, then retry. Do not paste the key in chat.': '请在本机运行 gemini extensions config nanobanana，配置 Google AI Studio 密钥后重试。不要把密钥发到聊天里。',
  'The image tool failed or was denied. This task has stopped; see details for the reason.': '画图工具执行失败或被拒绝，本次任务已停止，可展开详情查看原因。',
  'Grok stopped before completing the task': 'Grok 在任务完成前停止了',
  'This task is no longer running. See details before trying again.': '本次任务已停止，请查看详情后再重试。',
  'Planning the next steps': '正在规划下一步',
  'Compacting conversation context': '正在整理对话上下文',
  'Working on the task': '正在处理任务',
  'Connecting to local agent': '正在连接本地智能体',
  'Task received; getting started': '任务已提交，准备开始',
  'Waiting for new progress from local agent': '暂未收到新进展，仍在等待本地智能体',
  'Waiting for your approval; review the permission dialog': '等待你授权，请查看权限确认框',
  'Generating response content': '正在生成回复内容',
  'Local agent is running': '本地智能体正在运行',
  'Temporarily unavailable': '暂不可用', 'Excluded from group tasks until a successful health check': '暂停分配群任务，健康检测成功后恢复',
  'Group scheduler': '群调度', 'Decision service': '决策服务', 'Checking group member availability': '正在检查群成员状态',
  'Choosing a leader and reply order': '正在选择负责人和回复顺序', 'Preparing the task plan': '正在制定任务计划',
  'Arranging the next step after a member failure': '正在安排故障后的下一步',
  'Typing': '正在输入', 'Coordinating the group': '正在协调群聊', 'Preparing a greeting': '正在准备问候', 'Delivering a message': '正在传递消息', 'Preparing a reply': '正在回复', 'Thinking about the next step': '正在思考下一步', 'Preparing the result': '正在整理结果', 'Trying another approach': '正在尝试其他方法',
  'Actions performed': '执行的操作', 'the selected item': '所选项目', '{count} actions': '{count} 项操作', '{count} actions could not be completed': '{count} 项操作未完成',
  'Open local file': '打开本地文件', 'This file is no longer available at its saved location.': '文件已不在原来的位置。',
  'Opening {name} with the system default app': '正在用系统默认应用打开 {name}', 'Opened {name} with the system default app': '已用系统默认应用打开 {name}', 'Could not open {name} with the system default app': '未能用系统默认应用打开 {name}',
  'Checking files in {name}': '正在查看 {name} 中的文件', 'Checked files in {name}': '已查看 {name} 中的文件', 'Could not check files in {name}': '未能查看 {name} 中的文件',
  'Creating folder {name}': '正在创建文件夹 {name}', 'Created folder {name}': '已创建文件夹 {name}', 'Could not create folder {name}': '未能创建文件夹 {name}',
  'Moving {name}': '正在移动 {name}', 'Moved {name}': '已移动 {name}', 'Could not move {name}': '未能移动 {name}',
  'Opening {name}': '正在打开 {name}', 'Opened {name}': '已打开 {name}', 'Could not open {name}': '未能打开 {name}',
  'Contacting {name}': '正在联系 {name}', 'Contacted {name}': '已联系 {name}', 'Could not contact {name}': '未能联系 {name}',
  'Creating agent {name}': '正在创建智能体 {name}', 'Created agent {name}': '已创建智能体 {name}', 'Could not create agent {name}': '未能创建智能体 {name}',
  'Updating agent {name}': '正在修改智能体 {name}', 'Updated agent {name}': '已修改智能体 {name}', 'Could not update agent {name}': '未能修改智能体 {name}',
  'Working in the browser': '正在浏览器中操作', 'Completed a browser action': '已完成浏览器操作', 'Browser action failed': '浏览器操作失败',
  'Checking connected email': '正在查看已连接的邮箱', 'Checked connected email': '已查看已连接的邮箱', 'Could not check connected email': '未能查看已连接的邮箱',
  'Using a connected tool': '正在使用已连接工具', 'Completed a tool action': '已完成工具操作', 'Tool action failed': '工具操作失败',
  'Leave group': '退出群聊', 'Leave this group? Your agents will also leave.': '确定退出群聊？你带入群内的智能体也会一并退出。',
  'Search chat history': '查找聊天内容', 'View scheduled tasks': '查看定时任务', 'Clear chat history': '清空聊天记录', 'Clear all messages in this chat? This cannot be undone.': '确定清空当前聊天记录？此操作无法撤销。', 'No matching tasks': '没有匹配的任务', 'No matching messages': '暂无匹配消息', 'Showing latest 100 matches': '显示最近 100 条匹配消息', 'Could not load messages': '加载消息失败，请重试', 'Could not save changes': '保存失败，请重试',
  'Chat history with {name}': '与“{name}”的聊天记录', '{count} recent messages': '最近 {count} 条消息', 'No chat history yet': '还没有聊天记录', 'Try another keyword.': '换一个关键词试试。', 'Messages from this conversation will appear here.': '这个对话中的消息会显示在这里。',
  'Scheduled tasks for {name}': '“{name}”的定时任务', '{count} tasks': '共 {count} 个任务', 'No scheduled tasks in this chat': '这个聊天还没有定时任务', 'Ask this contact to remind you later or run something on a schedule.': '你可以让这个联系人稍后提醒你，或按计划定期执行任务。', 'Only tasks that post results to this conversation are shown.': '这里只显示会把结果发送到当前聊天的任务。',
  'Loading…': '加载中…', 'Load earlier messages': '加载更早的消息', 'Retry loading earlier messages': '加载失败，点击重试',
'Pin to top': '置顶',
'Unpin': '取消置顶',
'Mark as unread': '标为未读',
'Mark as read': '标为已读',
'Mute notifications': '消息免打扰',
'Unmute notifications': '取消免打扰',
'Open in separate window': '独立窗口显示',
'Hide chat': '不显示',
  'No conversation selected': '未选择对话',
  'Start chat': '发起聊天', 'No chats yet': '暂无聊天',
  'Filter chats': '筛选聊天', 'Filter chats: {filter}': '筛选聊天：{filter}',
  'Chat': '对话',
  'No unread chats': '暂无未读聊天', 'No direct chats': '暂无私聊', 'No group chats': '暂无群聊',
  'Could not mark chats as read': '无法标记为已读，请重试',
  'Create agent': '创建智能体', 'Agent name': '智能体名称', 'Enter agent name': '输入智能体名称', 'Runs with': '运行方式', 'Use cloud model': '使用云端模型', 'Use local agent': '使用本地智能体', 'Douchat cloud model': 'Douchat 云端模型', 'AI tools on this computer': '本机 AI 工具', 'Select a local agent': '选择本地智能体', 'No available local agents': '暂无可用的本地智能体', 'Douchat Cloud': 'Douchat 云端模型', 'Saving…': '保存中…', 'Close': '关闭',
  'Settings': '设置', 'Profile': '个人资料', 'Account': '账号', 'General': '通用', 'Agents': '智能体', 'Models': '模型', 'About': '关于', 'Update available': '有可用更新',
  'Usage & Billing': '用量与账单', 'Credits': '额度', 'Manage your Douchat credit balance.': '查看和充值你的 Douchat 额度。', 'Credit balance': '剩余额度', 'Top up': '充值', 'Top up credits': '去充值', 'Douchat does not have enough credits': 'Douchat 额度不足', 'Not enough Douchat credits': 'Douchat 额度不足', 'Top up credits to continue.': '请充值后继续对话。', 'Top up securely in your browser.': '将在浏览器中安全完成充值。', 'Your plan, balance, and billing in one place.': '查看套餐、剩余额度和账单。', 'Current plan': '当前套餐', 'Credits remaining': '剩余额度', 'Upgrade plan': '升级套餐', 'Manage plan': '管理套餐', 'Manage billing': '查看账单', 'Billing': '账单', 'Invoices and payment methods': '账单与支付方式', 'Billing is managed securely on douchat.ai.': '在 douchat.ai 安全管理账单和支付方式。', 'Active': '使用中', 'Trial': '试用中', 'Ends after this billing period': '将在本计费周期后结束', 'Free plan': '免费套餐', 'Free': '免费版',
  'Cloud agent replies use Douchat credits. Local agents do not.': '云端智能体回复会消耗额度，本地智能体不会消耗。', 'Sign in to view credits.': '登录后可查看额度。', 'Could not load credits. Check your connection and try again.': '无法加载额度，请检查网络后重试。', 'Sign in to view usage and billing.': '登录后可查看用量与账单。', 'Could not load usage and billing. Check your connection and try again.': '无法加载用量与账单，请检查网络后重试。', 'Your session has expired. Sign in again.': '登录状态已过期，请重新登录。', 'Try again': '重试',
  "Authorization expired. Reconnect this account.": "授权已失效，请重新连接。",
  "This account was disconnected.": "此账号已断开连接。",
  "Connection not found for this account.": "当前用户无法访问此连接。",
  "The connector service key needs administrator attention.": "连接服务密钥不可用，请联系管理员。",
  "An administrator needs to configure this connector.": "请管理员配置连接服务。",
  "This platform is not configured yet.": "此平台尚未配置。",
  "Cannot reach the connector service. Try again.": "无法访问连接服务，请重试。",
  "Too many requests. Wait a moment and retry.": "请求过于频繁，请稍后重试。",
  "Connect external accounts so your agents can read their data.": "连接外部账号，让你的智能体读取其中的数据。",
  "Finish connecting in your browser…": "请在浏览器中完成授权…",
  "Not configured": "尚未配置",
  "Not connected": "未连接",
  "Add account": "添加账号",
  "Stop waiting": "停止等待",
  "Authorization cancelled. You can connect again.": "授权已取消，可以重新连接。",
  "Authorization failed. Try connecting again.": "授权未完成，请重新连接。",
  "The link expired. Connect again to create a new link.": "链接已过期，请重新连接生成新链接。",
  "Disconnected": "已断开",
  "Reconnect required": "需要重新授权",
  "Reconnect": "重新连接",
  "Retry revocation": "重试撤销",
  "Disconnected locally. Platform revocation failed; retry or revoke access on the platform.": "本地已断开，但平台撤销失败，请重试或在平台撤销授权。",
  "Install GitHub App": "安装 GitHub App",
  "GitHub App installation may need organization approval. Ask your agent to refresh installations, then list repositories for the chosen installation.": "GitHub App 安装可能需要组织批准。请让智能体刷新安装列表，再读取所选安装下的仓库。",
  "Choose an account for each agent. Access is off by default.": "为每个智能体选择账号，默认不授权。",
  "No access": "不授权",
  "Create a cloud agent to grant access.": "创建云端智能体后即可授权。",
  "Read-only access. Connect another account to switch workspaces.": "仅支持读取。可添加其他账号以切换工作区。",
  "Read failed": "读取失败",
  "Reading…": "读取中…",
  "Refresh installations": "刷新安装列表",
  "Test read access": "验证读取权限",
  "GitHub installation": "GitHub 安装",
  "Choose an installation": "选择安装账号",
  "Read repositories": "读取仓库",
  "Read result": "读取结果",
  "Next page": "下一页",
  "Read your GitHub installations and repositories.": "读取 GitHub 中已授权的安装账号和仓库。",
  "Search shared pages and read page content in Notion.": "搜索 Notion 中已共享的页面，并读取页面内容。",
  "Read teams and issues in your Linear workspace.": "读取 Linear 工作区中的团队和议题。",
  "List installations": "查看安装列表",
  "List repositories": "查看仓库列表",
  "Search pages": "搜索页面",
  "Read page properties": "读取页面属性",
  "Read page content": "读取页面内容",
  "List teams": "查看团队列表",
  "List issues": "查看议题列表",
  "Manage repository access": "管理仓库授权",
  "Accounts": "账户",
  "Selected account": "已选账户",
  "Available to all contacts that support connector tools.": "默认供所有支持连接器工具的联系人使用。",
  "Choose an account to use with all contacts.": "选择供所有联系人使用的账户。",
  "Once connected, this account is available to all contacts that support connector tools.": "连接后，默认供所有支持连接器工具的联系人使用。",
  "Tools": "工具",
  "Enabled": "已启用",
  "Available tools": "可用工具",
  "Read only": "只读",
  "Apps": "应用",
  "Connector": "连接器",
  "Information": "信息",
  "Access": "访问权限",
  "Website": "网站",
  "Availability": "可用性",
  "Dismiss": "关闭提示",
  "This tool is unavailable. Refresh the connector tool list.": "该工具不可用，请重新获取连接器工具列表。",
  "This tool's parameters are not supported yet.": "暂不支持该工具的参数结构。",
  "Cannot reach the platform. Try again later.": "暂时无法访问平台，请稍后重试。",
  "Notion could not complete this request. Check the parameters and page access.": "Notion 未能完成请求，请检查参数和页面访问权限。",
  "Notion protocol error. Contact the connector administrator.": "Notion 协议错误，请联系连接器管理员。",
  "Notion returned an invalid response. Try again later.": "Notion 返回的数据无效，请稍后重试。",
  "No accounts connected": "无账号连接",
  "Rename account": "修改账号名称",
  "Disconnect this account? All contacts will lose access.": "确定断开此账号？断开后，所有联系人将无法再访问此账号。",
  "Disconnected locally. Platform revocation failed; remove app access on the platform.": "本地已断开，但平台撤销失败，请前往对应平台撤销应用授权。",
  'Use this account': '使用此账号',
  'Default account': '默认账号',
  'Set as default': '设为默认',
  'Uses the default account unless you name another connected account in chat.': '未指定账号时使用默认账号；对话中可指定其他已连接账号。',
  'Set a default account, or name a connected account in chat.': '请设置默认账号，也可在对话中指定已连接的账号。',
  'Connectors': '连接器', 'Connect accounts and let selected agents use their data and actions.': '连接外部账户，并让指定智能体使用其中的数据和操作。',
  'Connected accounts': '已连接账户', '{count} agents enabled': '已授权 {count} 个智能体', 'No agents enabled': '未授权智能体', 'Connected': '已连接',
  'Available connectors': '可用连接器', 'Built in': '内置', 'Connect': '连接',
  'Search, read, and summarize mail through IMAP. SMTP is verified for future sending support.': '通过 IMAP 搜索、阅读和总结邮件；同时验证 SMTP，为后续发送能力做好准备。',
  'Credentials stay encrypted on this computer': '凭据仅在本机加密保存',
  'Connectors are managed here because they belong to your account. Each agent still needs separate access.': '连接器属于你的账户，因此统一在这里管理；每个智能体仍需单独授权。',
  'Work email': '工作邮箱', 'Manage email': '管理邮箱', 'Connect email': '连接邮箱', 'Test both incoming and outgoing servers before saving.': '保存前会同时验证收件和发件服务器。',
  'Back to connectors': '返回连接器', 'Mailbox': '邮箱账户', 'This name and address identify the account to your agents.': '智能体将通过这个名称和地址识别邮箱。',
  'Account name': '账户名称', 'Email address': '邮箱地址', 'Provider': '服务商', 'Username': '用户名', 'Password or authorization code': '密码或授权码',
  'Feishu Mail': '飞书邮箱', 'Other IMAP/SMTP': '其他 IMAP/SMTP', 'Leave blank to keep the saved credential': '留空以保留已保存的凭据', 'Enter authorization code': '输入邮箱授权码',
  'Mail servers': '邮件服务器', 'TLS certificate verification is always enforced.': '始终强制验证 TLS 证书。', 'Port': '端口', 'Direct TLS': '安全连接',
  'Both servers are ready': '收件和发件服务器均已就绪', 'One or more servers could not connect': '一个或多个服务器连接失败',
  'Agent access': '智能体权限', 'Only selected agents receive email search and read tools.': '只有选中的智能体会获得邮件搜索和阅读工具。', 'Create a cloud agent before granting connector access.': '请先创建云端智能体，再授予连接器权限。',
  'Connection test failed': '连接测试失败', 'Email connection could not be saved': '无法保存邮箱连接', 'Email account could not be disconnected': '无法断开邮箱连接',
  'Disconnect this email account? Agents will immediately lose access.': '断开这个邮箱账户？智能体将立即失去访问权限。', 'Disconnect': '断开连接',
  'Testing…': '正在测试…', 'Connecting…': '正在连接…',
  'Complete the email address, username, and server settings.': '请填写完整的邮箱地址、用户名和服务器设置。', 'Enter the mailbox password or authorization code.': '请输入邮箱密码或授权码。',
  'Email connection failed.': '邮箱连接失败。', 'Email connection not found': '未找到邮箱连接', 'Email connection needs to be reconnected': '邮箱连接需要重新认证', 'Version': '版本', 'Checking for updates…': '正在检查更新…', 'Check for updates': '检查更新', 'You are up to date · Check again': '已是最新版本 · 再次检查', 'You are using the latest version.': '当前已是最新版本。', 'Update checks are available in packaged builds.': '当前为开发版；安装正式版后可检查更新。',
  'Downloading update…': '正在下载更新…', 'Downloading the verified update from Douchat…': '正在从 Douchat 正式发布渠道下载已验证的更新…', 'Connecting to the Douchat update service…': '正在连接 Douchat 更新服务…', 'Check for updates to compare this version with the latest release.': '检查更新以对比当前版本与最新正式版。', 'Version {version} is available': '发现新版本 {version}', 'Update to v{version} and restart': '更新到 v{version} 并重启', 'Update ready to install': '更新已准备好安装', 'Finish {count} active tasks before restarting.': '请先等待 {count} 个运行中的任务结束。', 'Restart to finish update': '重启并完成更新', 'Installing update and restarting…': '正在安装更新并重启…', 'Update failed:': '更新失败：',
  'Font size': '字体大小', 'Small': '小', 'Standard': '标准', 'Large': '大', 'Font preview': '字号预览', 'Messages and interface text update immediately.': '消息和界面文字将即时调整。',
  'Language': '语言', 'Appearance': '外观', 'Light': '浅色', 'Dark': '深色', 'System': '跟随系统', 'Follow system': '跟随系统',
  'Choose your language and appearance.': '设置界面语言和外观。',
  'Local agents': '本地智能体', 'View the local agents available on this computer.': '查看这台电脑上可用的本地智能体。',
  'Scheduling': '调度',
  'Installed': '已安装', 'Refresh': '刷新', 'Scanning…': '扫描中…', 'Detect': '检测', 'Detecting…': '检测中…',
  'Installed · uses your local login and default model': '已安装 · 使用本地登录和默认模型', 'Installed · chat adapter coming soon': '已安装 · 暂不支持聊天',
  'Checking your shell and installed commands…': '正在检测已安装的命令…', 'No supported local agents found. Install one in your terminal, then detect again.': '未检测到支持的本地智能体。请先在终端中安装，然后重新检测。',
  'Ready for chat': '可用于聊天', 'version unavailable': '未获取到版本', 'custom command': '自定义命令', 'login checked when first used': '首次使用时检查登录状态',
  'Desktop app found': '已发现桌面应用', 'CLI command not found': '未找到 CLI 命令', 'Desktop app only': '仅桌面应用', 'Desktop apps needing a CLI': '需要安装 CLI 的桌面应用',
  'Not detected': '未检测到', 'Expected CLI command': '需要的 CLI 命令', 'Other supported agents': '其他支持的智能体',
  'Custom local agent': '自定义本地智能体', 'The command receives the prompt as its final argument and must print the reply as plain text.': '命令会通过最后一个参数接收提示词，并需将纯文本回复输出到标准输出。',
  'Command or absolute path': '命令或绝对路径', 'Delete this custom local agent?': '确定删除这个自定义本地智能体吗？',
  'Could not add custom local agent.': '无法添加自定义本地智能体。', 'Could not remove custom local agent.': '无法移除自定义本地智能体。',
  'Remove contacts using this local agent before deleting it.': '请先移除使用这个本地智能体的联系人，再删除它。',
  'Enter a local agent name of 80 characters or fewer.': '请输入不超过 80 个字符的本地智能体名称。', 'Enter a valid executable command or absolute path.': '请输入有效的可执行命令或绝对路径。',
  'A command name cannot contain spaces. Use an absolute path instead.': '命令名不能包含空格，请改用绝对路径。', 'Up to 64 custom local agents can be registered.': '最多可以注册 64 个自定义本地智能体。',
  'Configure the endpoint used by model-based bots.': '配置智能体使用的模型服务。', 'Endpoint connected': '已连接模型服务', 'Model API connected': '模型 API 已连接', 'Using provider credentials from the environment': '使用环境变量中的服务商凭据', 'Connect an endpoint': '连接模型服务', 'Use an OpenAI-compatible model provider': '使用兼容 OpenAI 的模型服务', 'Configure': '配置', 'Cloud models are provided by your Douchat account.': 'Cloud 模型由你的 Douchat 账号提供。', 'Douchat Cloud connected': 'Douchat Cloud 已连接', 'Douchat Cloud unavailable': 'Douchat Cloud 暂不可用', 'Available cloud models': '可用 Cloud 模型：{count}',
  'Manage your account and chat identity.': '管理登录账号和聊天身份。', 'Your account identity is used everywhere in Douchat.': '头像和昵称将在 Douchat 各处保持一致。', 'Signed-in account': '当前登录账号', 'Signed in to Douchat': '已登录 Douchat', 'Sign out': '退出登录', 'Signing out…': '正在退出…', 'Could not sign out. Try again.': '退出登录失败，请重试。', 'Chat profile': '聊天身份',
  'Profile picture': '头像', 'Change your picture': '修改头像', 'PNG or JPG. Your picture is synced to your Douchat account.': '支持 PNG 或 JPG，保存后将同步到你的 Douchat 账号。', 'Email': '邮箱', 'Save changes': '保存修改', 'Saved to your Douchat account': '已同步到 Douchat 账号', 'Changes sync to every signed-in Douchat app.': '修改后会同步到所有已登录的 Douchat。', 'Could not save account changes.': '账号资料保存失败，请重试。', 'Name cannot be empty.': '名称不能为空。',
  'How you appear in every conversation.': '设置你在聊天中的头像和名称。', 'PNG or JPG. It is cropped to a square and stays on this computer.': '支持 PNG 或 JPG，图片将裁剪为正方形并保存在本机。', 'Choose picture': '选择图片', 'Remove': '移除', 'Display name': '显示名称', 'Name': '名称', 'Your name': '你的名称', 'Your bots address you by this name.': '智能体会使用这个名称称呼你。',
  'Resize sidebar': '调整侧边栏宽度', 'Search contacts': '搜索联系人', 'Clear search': '清除搜索', 'No agents match “{query}”.': '没有与“{query}”匹配的智能体。',
  'Add friend': '添加朋友', 'Status': '状态', 'Added': '已添加', 'Declined': '已拒绝', 'Awaiting acceptance': '待接受', 'Request sent': '已申请', 'Douchat user': 'Douchat 用户', 'Contact details': '联系人资料', 'Accept request': '接受申请', 'Decline request': '拒绝申请', 'Start group chat': '发起群聊', 'Select a contact to start chatting, or open an existing group.': '选择联系人开始聊天，或打开已有群聊。', '{count} pending friend requests': '{count} 条待处理好友申请', 'Friends': '朋友', 'Friend requests': '好友申请', 'No matching friends': '没有匹配的朋友', 'No friends yet': '暂无朋友', 'Create group with friends': '和朋友建群', 'Chats': '聊天', 'Contacts': '联系人', 'Search': '搜索', 'Search agents': '搜索智能体', 'New chat': '新建聊天', 'All chats': '全部聊天', 'Direct chats': '私聊', 'Group chats': '群聊', 'Unread': '未读', 'Mark all as read': '全部标为已读', 'New agent': '新建智能体', 'New group': '新建群聊', 'Working…': '正在处理…', 'Start a conversation': '开始聊天',
  'Save to contacts': '保存到通讯录', 'Remove from contacts': '从通讯录移除', 'Group menu': '群聊菜单', 'Chat details': '聊天详情', 'Group chat name': '群聊名称', 'Edit group chat name': '修改群聊名称', 'Add': '添加', 'Send message': '发送消息', 'No messages yet': '暂无消息', 'Emoji': '表情', 'Voice input': '语音输入', 'Start voice input': '开始语音输入', 'Stop voice input': '停止语音输入', 'Listening…': '正在听…', 'Starting microphone…': '正在启动麦克风…', 'Finishing voice input…': '正在结束语音输入…', 'Manage agents': '管理智能体', 'Cancel': '取消', 'Save': '保存', 'Edit': '编辑', 'Delete': '删除',
  'Today': '今天', 'Yesterday': '昨天', 'now': '刚刚', 'You': '你', 'Everyone': '所有人',
  'Something went wrong': '遇到了错误', 'Hide': '收起', 'Details': '详情', 'Quote': '引用', 'Cancel quote': '取消引用', 'Image preview': '图片预览', 'View image': '查看图片', 'Copy image': '复制图片', 'Image could not be copied': '图片复制失败', 'Message actions': '消息操作', 'Could not copy message': '复制消息失败', 'Could not delete message': '删除消息失败', 'Invite to group': '邀请入群', 'Share this link to invite people to the group': '分享链接，邀请其他人加入群聊', 'Invitation expired': '邀请已过期', 'Invitation link': '邀请链接', 'Copy link': '复制链接', 'Save image': '保存图片', 'Image saved': '图片已保存', 'Could not create invitation': '无法生成邀请，请重试', 'Regenerate invitation': '重新生成邀请', 'Confirm regeneration': '确认重新生成', 'Invitation link updated': '邀请链接已更新，旧链接已失效', 'The old invitation link will stop working.': '重新生成后，旧邀请链接将立即失效。', 'Anyone with this invitation can join after signing in. New members only see messages sent after joining.': '持有此邀请的人登录后即可入群。新成员仅能查看入群后的消息。', 'Never expires': '永不过期', 'Valid until {date}': '有效期至 {date}', 'Copy': '复制', 'Copied': '已复制', 'Send': '发送', 'Stop': '停止', 'Retry': '重试',
  'Claude Code could not be found': '未找到 Claude Code',
  'Install Claude Code, then open Settings → Local agents and detect it again.': '请先安装 Claude Code，然后打开“设置 → 本地智能体”重新检测。',
  'OMP’s Anthropic API credit is insufficient': 'OMP 的 Anthropic API 额度不足',
  'Select the model you use in OMP, or top up that provider’s API balance. Douchat credits do not cover local agent usage.': '请选择你在 OMP 中使用的模型，或补充对应服务商的 API 额度。本地智能体不使用 Douchat 额度。',
  'OpenClaw cannot authenticate with the selected model': 'OpenClaw 当前模型的认证不可用',
  'Configure authentication for this model in OpenClaw, or select a model already configured there, then try again.': '请在 OpenClaw 中完成当前模型的认证，或选择已配置好认证的模型，然后重试。',
  'OpenClaw needs a local data upgrade': 'OpenClaw 本地数据需要升级',
  'Stop active OpenClaw tasks, run openclaw doctor --fix in Terminal, then try again.': '请先停止正在运行的 OpenClaw 任务，在终端执行 openclaw doctor --fix，再重试。',
  'Claude Code is not signed in': 'Claude Code 尚未登录',
  'Open Claude Code in Terminal and sign in, then return to Douchat and try again.': '请在终端打开 Claude Code 并完成登录，然后回到 Douchat 重试。',
  'Claude Code does not have enough credit': 'Claude Code 额度不足',
  'Open Claude Code in Terminal and add credit or switch to an account with available usage, then return to Douchat and try again.': '请在终端打开 Claude Code，补充额度或切换到有可用额度的账号，然后回到 Douchat 重试。',
  'Grok cannot start with the current Docker socket setup': 'Grok 暂时无法启动：与 Docker 环境不兼容',
  'Grok could not start its sandbox': 'Grok 的安全环境启动失败',
  'Grok’s sandbox rejected a Docker socket link before the conversation started. Try updating Grok. If it still fails, use another agent while this compatibility issue is resolved.': 'Grok 的安全检查不支持当前 Docker 连接方式，对话尚未开始。可以先更新 Grok；若仍报错，请暂时使用其他智能体。',
  'Grok stopped before the conversation started because its sandbox could not be applied. Try updating Grok; technical details are available below.': 'Grok 未能启用安全保护，对话尚未开始。可以先更新 Grok，或展开详情查看原因。',
  'Update Grok': '更新 Grok',
  'Could not open the updater. Try Settings → Local agents.': '无法打开更新，请到「设置 → 本地智能体」重试。',
  'Open Claude Code': '打开 Claude Code', 'Could not open Claude Code. Open a terminal and run claude manually.': '无法自动打开 Claude Code，请手动打开终端并运行 claude。', 'Opening Claude Code timed out. Try again or run claude in a terminal manually.': '打开 Claude Code 超时。请重试，或在终端中手动运行 claude。',
  'Claude Code could not start': 'Claude Code 启动失败',
  'Open Claude Code in Terminal once. Finish signing in or fix the error shown there, then return to Douchat and try again.': '请先在终端运行一次 Claude Code，完成登录或处理终端显示的问题，然后回到 Douchat 重试。',
  'View source': '查看源码', 'Mermaid diagram could not be rendered': 'Mermaid 图表无法渲染', 'SVG image': 'SVG 图像', 'SVG could not be rendered safely. Check the code format.': 'SVG 无法安全渲染，请检查代码格式。',
  'Enlarge diagram': '放大图表', 'Close enlarged diagram': '关闭大图', 'Zoom in': '放大', 'Zoom out': '缩小', 'Reset view': '复位',
  'Open preview': '打开预览', 'Opening…': '正在打开…', 'Code preview could not be opened': '无法打开代码预览',
  'Open {name} in a separate window': '在独立窗口打开 {name}', '{count} lines': '{count} 行', 'lines': '行',
  'Preview': '效果', 'Source code': '源码', 'Copy source': '复制源码', 'Reload preview': '重新加载效果', 'Reload': '重新加载',
  'Code preview views': '代码预览视图', 'Rendered preview': '渲染效果', 'Loading preview…': '正在加载预览…',
  'This code preview is no longer available.': '此代码预览已失效，请从消息中重新打开。',
  'Private from {name}': '来自 {name} 的私信', 'Received privately from {name}': '收到来自 {name} 的私信', 'Private message from': '私信来自', 'Private message from {name}': '来自 {name} 的私信', 'From': '来自', 'From {name}': '来自 {name}', 'Private message to': '发送私信给', 'Private message details are unavailable.': '这条历史私信没有保存详情。', '{name} replied': '{name} 回复', 'Via {name}': '由 {name} 转达', 'Sent privately to {name}': '已私信发送给 {name}', 'Sent private message to {names}': '已发送私信给 {names}', 'Private message to {name}': '发送给 {name} 的私信', 'To': '发送给', 'To {name}': '发送给 {name}', 'Show private messages': '展开私信内容', 'Hide private messages': '收起私信内容', 'Handoff': '转交',
  'Invited {names} to participate': '已邀请 {names} 参与',
  'Continue chatting with {name}': '继续向 {name} 追问',
  'Show invitation details': '展开邀请详情', 'Hide invitation details': '收起邀请详情',
  'Waiting for acceptance': '等待接单', 'Processing invitation': '处理中',
  'Invitation failed': '邀请处理失败', 'Invitation completed': '已完成',
  'Message {name}': '给 {name} 发消息', 'Message {name} · @ to mention': '给 {name} 发消息 · 输入 @ 提及成员', 'Create an agent to start chatting': '创建智能体后开始聊天',
  'Send a message to {name}.': '给 {name} 发送一条消息。', 'Send a message to {name}, or @ a member to address them directly.': '给 {name} 发送消息，或输入 @ 直接提及成员。',
  'Choose a local agent or connect a model endpoint to start chatting.': '请选择本地智能体或连接模型服务后开始聊天。', 'Choose agent': '选择智能体',
  'Mention a member': '提及成员', 'Choose an emoji': '选择表情', 'Stop the current reply': '停止当前回复',
  'Image could not be loaded': '图片加载失败', 'Loading image': '正在加载图片', 'Agent generated image': '智能体生成的图片',
  'Images ready to send': '待发送图片', 'Pasted image': '粘贴的图片', 'Remove image': '移除图片',
  'Only PNG, JPEG, WebP, and GIF images are supported.': '仅支持 PNG、JPEG、WebP 和 GIF 图片。', 'Each image must be 8 MB or smaller.': '每张图片不能超过 8 MB。',
  'You can paste up to 4 images at a time.': '一次最多可粘贴 4 张图片。', 'Images must total 20 MB or less.': '图片总大小不能超过 20 MB。', 'Unsupported image format': '不支持的图片格式',
  'Pasted image could not be read.': '无法读取粘贴的图片。',
  'Microphone access is off. Allow {name} in System Settings, then restart the app.': '麦克风权限未开启。请在系统设置中允许 {name} 使用麦克风，然后重启应用。',
  'Microphone permission changed. Restart Douchat and try again.': '麦克风权限已变更。请重启 Douchat 后重试。',
  'Voice recognition service is unavailable in this version of Douchat.': '当前版本的 Douchat 无法使用语音识别服务。',
  'Open System Settings': '打开系统设置',
  'Voice input is unavailable in this version of Douchat.': '当前版本的 Douchat 无法使用语音输入。',
  'Voice input could not start. Try again.': '无法启动语音输入，请重试。',
  'No microphone was found.': '未找到可用的麦克风。',
  'No speech was detected. Try again.': '没有识别到语音，请重试。',
  'Voice recognition could not connect. Check your network and try again.': '语音识别服务连接失败，请检查网络后重试。',
  'Voice input stopped unexpectedly. Try again.': '语音输入意外停止，请重试。',
  'Invalid image attachments': '图片附件无效',
  '{name} is unavailable — {replacement} is standing in.': '{name} 当前不可用，由 {replacement} 暂时代替。',
  'No chats match “{query}”.': '没有与“{query}”匹配的聊天。', 'You: {message}': '你：{message}',
  'Put several agents in one room': '让多个智能体加入同一个群聊', 'Starred': '已置顶',
  'Pick an agent or a group to see its profile.': '选择一个智能体或群聊以查看资料。', 'Members': '成员', 'How this group works': '群聊运行方式',
  'The lead member opens the conversation, dispatches work and consolidates the result. Mention a member with @ to address them directly.': '主智能体负责开启对话、分配工作并汇总结果。输入 @ 可直接指定成员。',
  'Open the group chat': '进入群聊', 'Manage members': '管理成员', 'What this group is for': '群聊用途', 'topics': '个话题', 'members': '位成员',
  'Edit group': '编辑群聊', 'Lead member': '主智能体', 'Add a member': '添加成员',
  'Opening Douchat…': '正在打开 Douchat…', 'Close chat details': '关闭聊天详情', '{name} — open your profile': '{name} — 打开个人资料', '{name} — view profile': '{name} — 查看资料',
  'Close window': '关闭窗口', 'Minimize window': '最小化窗口', 'Toggle full screen': '切换全屏', 'Window controls': '窗口控制', 'Sections': '功能导航',
  'Message could not be sent': '消息发送失败', 'Agent could not be deleted': '无法删除智能体', 'Chat could not be deleted': '无法删除聊天', 'Chat could not be opened': '无法打开聊天', 'Chat could not be pinned': '无法更改置顶状态', 'Chat could not be updated': '无法更新聊天', 'Window could not be opened': '无法打开独立窗口',
  '{name} joined the workspace': '{name} 已加入工作区', '{name} updated': '已更新 {name}', 'Delete {name}? Their chat and group memberships are removed.': '确定删除 {name}？其私聊和群聊成员关系也会被移除。', '{name} was removed': '已移除 {name}', '{name} is ready': '{name} 已创建', 'Group updated': '群聊已更新',
  'Automation': '自动化', 'Create a routine': '创建例行任务', 'What should happen?': '需要执行什么？', 'Post results to': '将结果发送到', 'Schedule': '计划',
  'Scheduled tasks created from your conversations.': '管理从对话中创建的定时任务。', 'No scheduled tasks yet': '还没有定时任务', 'Ask any contact to remind you later or run something on a schedule.': '你可以让任何联系人稍后提醒你，或按计划定期执行任务。',
  'Once': '单次', 'Every {count} minutes': '每 {count} 分钟', 'Every {count} hours': '每 {count} 小时', 'Every {count} days': '每 {count} 天',
  'Sun': '周日', 'Mon': '周一', 'Tue': '周二', 'Wed': '周三', 'Thu': '周四', 'Fri': '周五', 'Sat': '周六',
  'Completed': '已完成', 'Expired': '已过期', 'Paused': '已暂停', 'Running': '执行中', 'Retrying': '等待重试', 'Failed': '失败', 'Unknown agent': '未知智能体', 'Unknown conversation': '未知对话',
  'Next run: {time}': '下次执行：{time}', 'Last run: {time}': '上次执行：{time}', 'Run now': '立即运行', 'Pause': '暂停', 'Resume': '恢复', 'Delete this automation?': '确定删除这个自动任务吗？',
  'If Douchat is not running when a task is due, it runs once after the next launch.': '如果任务到期时 Douchat 未运行，会在下次启动后补执行一次。',
  'e.g. Review the morning brief': '例如：查看晨间简报', 'Give the agent a complete instruction, including the expected result.': '请提供完整指令，并说明期望的结果。',
  'Every day': '每天', 'Weekdays': '工作日', 'Every week': '每周', 'Repeating interval': '按间隔重复', 'Every 15 minutes': '每 15 分钟', 'Every 30 minutes': '每 30 分钟', 'Every hour': '每小时', 'Every 6 hours': '每 6 小时', 'Every 12 hours': '每 12 小时',
  'The app must be running. Missed times run once when the computer wakes.': '应用需要保持运行；电脑唤醒后会补执行一次错过的任务。',
  'Base URL': '基础 URL', 'API key': 'API 密钥', "Stored on this computer, in the app's own data folder.": '保存在此电脑的 Douchat 数据目录中。',
  'Invalid attachment id': '附件编号无效', 'Attachment not found': '未找到附件', 'Conversation not found': '未找到对话', 'This conversation is still replying': '当前对话仍在回复中',
  'Unknown local agent': '未知的本地智能体', 'This local agent has no chat adapter yet': '该本地智能体暂不支持聊天', 'Local agent failed': '本地智能体运行失败', 'OpenCode failed': 'OpenCode 运行失败',
  'Routine name and instructions are required': '请输入例行任务名称和指令', 'Routine agent not found': '未找到例行任务的智能体', 'Routine conversation not found': '未找到例行任务的对话', 'Routine interval must be at least one minute': '例行任务的间隔不能少于一分钟', 'Choose at least one day and a valid time': '请选择至少一天并设置有效时间', 'Routine not found': '未找到例行任务',
  'A group needs at least one bot': '群聊至少需要一个智能体', 'Chat not found': '未找到聊天', 'Agent not found': '未找到智能体',
  'a contact': '联系人', '{count} members': '{count} 位成员', '{count} topics': '{count} 个话题',
  'Connected · {count} models': '已连接 · {count} 个模型', 'Endpoint saved': '模型服务已保存',
  'Installed agents': '已安装的本地智能体',
  'Untitled routine': '未命名例行任务', 'Choose an agent': '选择智能体', '{name} will run this in a private computer.': '{name} 将在专属电脑中执行此任务。',
  'Times use {timezone}.': '时间采用 {timezone} 时区。', 'Creating…': '正在创建…', 'Create routine': '创建例行任务',
  'Creating routine {name}': '正在创建自动任务“{name}”', 'Created routine {name}': '已创建自动任务“{name}”', 'Could not create routine {name}': '无法创建自动任务“{name}”',
  'Sunday': '星期日', 'Monday': '星期一', 'Tuesday': '星期二', 'Wednesday': '星期三', 'Thursday': '星期四', 'Friday': '星期五', 'Saturday': '星期六',
  'Not connected yet': '尚未连接', '{count} chat models available': '有 {count} 个聊天模型可用',
  'Currently read from .env — saving here overrides it.': '当前从 .env 读取；在此保存后将覆盖该配置。', 'Any OpenAI-compatible base URL works, including a local router.': '支持任何兼容 OpenAI 的基础 URL，包括本地路由服务。',
  'Saved — type to replace it': '已保存；输入新密钥即可替换', 'Reached the endpoint · {count} chat models': '已连接模型服务 · {count} 个聊天模型', 'Test connection': '测试连接', 'Checking…': '正在检查…', 'Save and connect': '保存并连接',
  'This window is newer than the running app. Quit and start it again (npm run dev).': '当前窗口比正在运行的主程序更新。请退出并重新启动应用（npm run dev）。',
  'Choose an image file.': '请选择图片文件。', 'This picture could not be prepared.': '无法处理这张图片。', 'This picture could not be read.': '无法读取这张图片。', 'Could not save agent': '智能体保存失败', 'Could not detect local agents. Try Detect again.': '无法检测本地智能体，请重新检测。'
}
