/** Local application errors; remote provider diagnostics are preserved verbatim. */
export const runtimeTranslations: Record<string, string> = {
  "The selected agent is no longer a member of this group.": "所选 Agent 已不在这个群里。",
  "This mention matches multiple members. Use a unique member name or select a task recipient.": "这个 @ 对应多个同名成员，请使用不重名的成员名称，或选择任务接收者。",
  "Message not sent. Try again.": "消息未发送，请重试。",
  "Sign in first.": "请先登录。",
  "Sign in to Foundry first.": "请先登录 Foundry。",
  "This group task does not belong to the current account.": "群任务不属于当前账号。",
  "The original group task message was deleted.": "群任务的原始消息已删除。",
  "You may only add and run your own agents.": "只能添加和执行自己的 agent。",
  "The custom model was removed or is unavailable. Reconfigure it in settings.": "自定义模型已移除或不可用，请到设置中重新配置。",
  "The cloud model is unavailable. Refresh the model list and try again.": "云端模型不可用，请刷新模型列表后重试。",
  "The custom model was removed or is unavailable. Reconfigure it in Settings → Custom models.": "自定义模型已移除或不可用，请到「设置 → 自定义模型」重新配置。",
  "This agent does not belong to the current account.": "Agent 不属于当前账号。",
  "This agent is busy. Try again after the current task finishes.": "Agent 正在处理其他任务，请稍后重新发送。",
  "Task cancelled.": "任务已取消。",
  "Task completed.": "任务已完成。",
  "Cloud decision models could not be loaded. Try again later.": "暂时无法加载云端决策模型，请稍后重试。",
  "The cloud decision model is unavailable. Using the default decision mode.": "云端决策模型暂不可用，将使用默认决策方式。",
  "The sign-in session changed. Try again.": "登录状态已变化，请重试。",
  "Invalid provider ID.": "服务商标识无效。",
  "Select an API type.": "请选择 API 类型。",
  "Enter a provider name.": "请输入服务商名称。",
  "Invalid configuration format.": "配置格式无效。",
  "The API URL must use HTTP or HTTPS and contain no password, query parameters or fragment.": "API 地址必须是 HTTP 或 HTTPS 地址，不能包含密码、查询参数或片段。",
  "Enter valid model names, one per line.": "请输入有效模型名称，每行一个。",
  "Invalid model configuration.": "模型配置无效。",
  "The API URL changed. Enter the API key again.": "API 地址已修改，请重新输入密钥。",
  "Enter an API key.": "请输入 API 密钥。",
  "Duplicate provider IDs.": "服务商标识重复。",
  "Select a model from the configuration.": "请选择配置中的模型。",
  "System credential storage is unavailable. Enable the system keychain and try again.": "系统密钥存储不可用，请启用系统钥匙串后重试。",
  "Sign in with the same account used to join this group.": "请使用加入群聊的同一账号登录。",
  "Select one execution mode.": "请选择一种运行方式。",
  "Select one model source.": "请选择一种模型来源。",
  "The account changed. Try again.": "账号已切换，请重试。",
  "Your session expired. Sign in again.": "登录已过期，请重新登录。",
  "The chat service connection failed. Try again later.": "聊天服务连接失败，请稍后重试。",
  "Images are not yet supported in shared group chats.": "群聊暂不支持图片。",
  "Unsupported operation.": "不支持的操作。",
  "The group member has not been removed. Refresh and try again.": "群成员尚未移除，请刷新后重试。",
  "Wait for the current reply to finish before inviting friends.": "请等当前回复完成后再邀请好友。",
  "Task permission check failed.": "任务权限校验失败。",
  "The local runtime has not been initialized.": "本地运行环境尚未初始化。",
  "Runtime download verification failed. Try again.": "运行环境下载校验失败，请重试。",
  "Automatic Node.js setup does not support this architecture. Install Node.js 24 manually.": "当前系统架构暂不支持自动准备 Node.js，请手动安装 Node.js 24。",
  "The runtime could not start. Check system compatibility.": "运行环境无法启动，请检查系统兼容性。",
  "Could not open the system terminal. Open Terminal and try again, or copy and run the command from the confirmation dialog.": "无法打开系统终端。请打开 Terminal 后重试，或复制确认窗口中的命令手动执行。",
  "Runtime download failed ({status}). Check your connection and try again.": "运行环境下载失败（{status}），请检查网络后重试。"
}
